#!/usr/bin/env bash
# Build all three local targets for mario-clone: Linux, Web, Android.
#
# Run this ONLY with the Godot editor closed — a second Godot process on an
# open project corrupts the .godot/ caches.
#
#   bash projects/mario-clone/build.sh            # all three
#   bash projects/mario-clone/build.sh web         # just one (linux | web | android)
#
# Art/audio are generated by the Python scripts in tools/ and committed as
# PNG/WAV/OGG — this script does NOT regenerate them (see CLAUDE.md).
set -e

GODOT=~/GodotDev/learn_2d_gamedev_godot_4_0.57.0_linux/godot
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ADB=~/Android/Sdk/platform-tools/adb
targets="${*:-linux web android}"

cd "$HERE"

# Only real godot processes count (a plain `ps | grep` would also match any
# shell whose command line merely contains the pattern).
for pid in $(pgrep -x godot) $(pgrep -x godot-nvidia); do
  args="$(tr '\0' ' ' < /proc/$pid/cmdline 2>/dev/null)"
  cwd="$(readlink /proc/$pid/cwd 2>/dev/null)"
  if [[ "$args" == *--editor* || "$args" == *" -e "* ]] && [[ "$args$cwd" == *mario-clone* ]]; then
    echo "Godot editor (pid $pid) is open on this project — close it first." >&2
    exit 1
  fi
done

# help images: rasterise SVG -> PNG, then let Godot import everything
[ -x assets/help_src/render.sh ] && bash assets/help_src/render.sh
"$GODOT" --headless --path . --import

for t in $targets; do
  case "$t" in
    linux)
      "$GODOT" --headless --path . --export-release "Linux" ../mario-clone-linux.x86_64
      chmod +x ../mario-clone-linux.x86_64
      ;;
    web)
      mkdir -p ../web-release-mario-clone
      "$GODOT" --headless --path . --export-release "Web" ../web-release-mario-clone/index.html
      ;;
    android)
      "$GODOT" --headless --path . --export-release "Android" ../mario-clone-android.apk
      if "$ADB" get-state >/dev/null 2>&1; then
        "$ADB" install -r ../mario-clone-android.apk
      else
        echo "  (no device connected — APK built, not installed)"
      fi
      ;;
    *) echo "unknown target: $t" ;;
  esac
done

# The godot_mcp addon strips its own [autoload] entries on every editor-context
# run (--import/--export*) — see the learn-path CLAUDE.md. Restore them.
python3 tools/fix_mcp_autoloads.py project.godot

echo
echo "done: $targets"
