class_name DecorIndex

## Generated by tools/gen_tiles.py — do not edit by hand.
## name -> Rect2 inside res://assets/graphics/decor.png

const RECTS := {
	"bush_l": Rect2(0, 0, 34, 13),
	"bush_s": Rect2(35, 0, 20, 12),
	"flower_a": Rect2(56, 0, 4, 6),
	"flower_b": Rect2(61, 0, 4, 6),
	"flower_c": Rect2(66, 0, 4, 6),
	"tuft": Rect2(71, 0, 8, 4),
	"rock": Rect2(80, 0, 10, 7),
	"sign": Rect2(91, 0, 14, 15),
	"fence": Rect2(106, 0, 16, 9),
	"castle": Rect2(123, 0, 80, 88),
	"cactus_l": Rect2(204, 0, 16, 28),
	"cactus_s": Rect2(221, 0, 12, 12),
	"dflower": Rect2(234, 0, 4, 6),
	"tuft_sand": Rect2(239, 0, 8, 4),
	"rock_sand": Rect2(248, 0, 10, 7),
	"pine": Rect2(259, 0, 20, 32),
	"bush_snow": Rect2(280, 0, 20, 12),
	"frost": Rect2(301, 0, 12, 13),
	"tuft_snow": Rect2(314, 0, 8, 4),
	"rock_snow": Rect2(323, 0, 10, 7),
	"crystal_l": Rect2(334, 0, 20, 22),
	"crystal_s": Rect2(355, 0, 12, 13),
	"glowshroom": Rect2(368, 0, 10, 9),
	"tuft_cave": Rect2(379, 0, 8, 4),
	"rock_cave": Rect2(388, 0, 10, 7),
	"pole": Rect2(399, 0, 4, 16),
	"pole_ball": Rect2(404, 0, 8, 8),
	"flag": Rect2(413, 0, 17, 15),
	"castle_flag": Rect2(431, 0, 10, 8),
	"cp_off": Rect2(442, 0, 14, 18),
	"cp_on": Rect2(457, 0, 14, 18),
}
