class_name DecorIndex

## Generated by tools/gen_tiles.py — do not edit by hand.
## name -> Rect2 inside res://assets/graphics/decor.png

const RECTS := {
	"bush_l": Rect2(0, 0, 34, 13),
	"bush_s": Rect2(35, 0, 20, 12),
	"flower_a": Rect2(56, 0, 4, 6),
	"flower_b": Rect2(61, 0, 4, 6),
	"flower_c": Rect2(66, 0, 4, 6),
	"tuft": Rect2(71, 0, 8, 4),
	"rock": Rect2(80, 0, 10, 7),
	"sign": Rect2(91, 0, 14, 15),
	"fence": Rect2(106, 0, 16, 9),
	"castle": Rect2(123, 0, 80, 88),
	"pole": Rect2(204, 0, 4, 16),
	"pole_ball": Rect2(209, 0, 8, 8),
	"flag": Rect2(218, 0, 17, 15),
	"castle_flag": Rect2(236, 0, 10, 8),
	"cp_off": Rect2(247, 0, 14, 18),
	"cp_on": Rect2(262, 0, 14, 18),
}
