extends Node

## Autoload "Snd". One AudioStreamPlayer per sound key, per-sound volume
## 0-100 % persisted in user://settings.cfg [sound] (global CLAUDE.md #8),
## global mute via the Master bus (#15). All clips are original, generated by
## tools/gen_audio.py into res://assets/sounds (SFX, .wav) and
## res://assets/music (.ogg).
##
## Music keys are exclusive: play_music() stops whatever music was running.
## Access from class_name scripts via get_node_or_null("/root/Snd") — the bare
## "Snd" identifier does not resolve under `godot --script` (_selftest).

const CFG_PATH := "user://settings.cfg"
const CALIB_VERSION := 1

# key -> [display name, default %, base_db calibration]
const SOUNDS := {
	"music_overworld": ["Music: Green Hills", 55, -4.0],
	"music_cave": ["Music: Coin Cave", 55, -4.0],
	"music_star": ["Music: Star Power", 55, -4.0],
	"music_title": ["Music: Title", 55, -4.0],
	"music_desert": ["Music: Dune Drift", 55, -4.0],
	"music_snow": ["Music: Frosty Peaks", 55, -4.0],
	"music_castle": ["Music: Castle", 55, -4.0],
	"jingle_world": ["Jingle: World Clear", 70, -4.0],
	"jingle_clear": ["Jingle: Course clear", 60, -3.0],
	"jingle_death": ["Jingle: Lost a life", 60, -3.0],
	"jingle_gameover": ["Jingle: Game over", 60, -3.0],
	"jump": ["Jump", 55, -6.0],
	"jump_big": ["Jump (big)", 55, -6.0],
	"stomp": ["Stomp", 60, -3.0],
	"kick": ["Enemy knocked out", 60, -4.0],
	"bump": ["Block bump", 60, -4.0],
	"break": ["Brick break", 60, -3.0],
	"coin": ["Coin", 55, -5.0],
	"sprout": ["Item appears", 60, -4.0],
	"powerup": ["Power-up", 60, -4.0],
	"powerdown": ["Power-down / pipe hit", 60, -4.0],
	"oneup": ["Extra life", 60, -3.0],
	"fireball": ["Fireball", 55, -6.0],
	"pipe": ["Pipe travel", 60, -4.0],
	"flagpole": ["Flag pole", 60, -4.0],
	"tick": ["Time bonus tick", 45, -8.0],
	"skid": ["Skid", 45, -8.0],
	"hatch": ["Egg hatch", 60, -4.0],
	"dino": ["Dragon mount", 60, -4.0],
	"tongue": ["Dragon tongue", 55, -5.0],
	"gulp": ["Dragon gulp", 60, -4.0],
	"checkpoint": ["Checkpoint", 60, -4.0],
	"hurry": ["Hurry up!", 60, -3.0],
	"pause": ["Pause", 50, -6.0],
}
const ORDER := [
	"music_overworld", "music_cave", "music_desert", "music_snow", "music_castle", "music_star", "music_title",
	"jingle_world",
	"jingle_clear", "jingle_death", "jingle_gameover",
	"jump", "jump_big", "stomp", "kick", "bump", "break", "coin", "sprout",
	"powerup", "powerdown", "oneup", "fireball", "pipe", "flagpole", "tick",
	"skid", "hatch", "dino", "tongue", "gulp", "checkpoint", "hurry", "pause",
]
const MUSIC_KEYS := ["music_overworld", "music_cave", "music_desert", "music_snow", "music_castle", "music_star", "music_title"]

var _muted := false
var _players := {}
var _vol := {}
var _previewing := ""
var _music := ""
var _music_pitch := 1.0

func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	_load()
	AudioServer.set_bus_mute(AudioServer.get_bus_index("Master"), _muted)
	for key in SOUNDS:
		var p := AudioStreamPlayer.new()
		p.name = key
		var stream := _find_stream(key)
		if stream:
			if key in MUSIC_KEYS and stream is AudioStreamOggVorbis:
				(stream as AudioStreamOggVorbis).loop = true
			p.stream = stream
		add_child(p)
		_players[key] = p
		_apply(key)

func _find_stream(key: String) -> AudioStream:
	for path in ["res://assets/music/%s.ogg" % key, "res://assets/sounds/%s.wav" % key,
			"res://assets/sounds/%s.ogg" % key]:
		if ResourceLoader.exists(path):
			return load(path)
	return null

func play(key: String) -> void:
	var p = _players.get(key)
	if p and p.stream:
		p.play()

func stop(key: String) -> void:
	var p = _players.get(key)
	if p:
		p.stop()

func play_music(key: String, pitch := 1.0) -> void:
	if _music == key and _players.has(key) and _players[key].playing:
		set_music_pitch(pitch)
		return
	stop_music()
	_music = key
	var p = _players.get(key)
	if p and p.stream:
		p.pitch_scale = pitch
		_music_pitch = pitch
		p.play()

func set_music_pitch(pitch: float) -> void:
	_music_pitch = pitch
	var p = _players.get(_music)
	if p:
		p.pitch_scale = pitch

func stop_music() -> void:
	for k in MUSIC_KEYS:
		var p = _players.get(k)
		if p:
			p.stop()
	_music = ""

func pause_music(paused: bool) -> void:
	var p = _players.get(_music)
	if p:
		p.stream_paused = paused

func current_music() -> String:
	return _music

func stop_all() -> void:
	for k in _players:
		_players[k].stop()
	_music = ""

func is_muted() -> bool:
	return _muted

func toggle_mute() -> bool:
	set_muted(not _muted)
	return _muted

func set_muted(m: bool) -> void:
	_muted = m
	AudioServer.set_bus_mute(AudioServer.get_bus_index("Master"), m)
	_save()

func get_volume(key: String) -> int:
	return int(_vol.get(key, SOUNDS[key][1]))

func set_volume(key: String, pct: int) -> void:
	_vol[key] = clampi(pct, 0, 100)
	_apply(key)
	_save()

func preview_exclusive(key: String) -> void:
	stop_preview()
	var p = _players.get(key)
	if p and p.stream:
		p.play()
		_previewing = key

func stop_preview() -> void:
	if _previewing == "":
		return
	var p = _players.get(_previewing)
	if p and _previewing != _music:
		p.stop()
	_previewing = ""

func _apply(key: String) -> void:
	var p = _players.get(key)
	if not p:
		return
	var pct := get_volume(key)
	if pct <= 0:
		p.volume_db = -80.0
	else:
		p.volume_db = float(SOUNDS[key][2]) + linear_to_db(pct / 100.0)

func _load() -> void:
	var c := ConfigFile.new()
	if c.load(CFG_PATH) != OK:
		return
	_muted = c.get_value("sound", "muted", false)
	if c.get_value("sound", "calib_version", 0) != CALIB_VERSION:
		return
	for key in SOUNDS:
		_vol[key] = c.get_value("sound", key, SOUNDS[key][1])

func _save() -> void:
	var c := ConfigFile.new()
	c.load(CFG_PATH)
	c.set_value("sound", "calib_version", CALIB_VERSION)
	c.set_value("sound", "muted", _muted)
	for key in _vol:
		c.set_value("sound", key, _vol[key])
	c.save(CFG_PATH)
