class_name WorldMapData

## Generated by tools/gen_map.py — do not edit by hand.
## NODES: course markers in game.gd LEVELS order; ROADS[i]: polyline from
## course i to course i+1; ROAD_KIND[i]: its look (dirt / cloud / plank).

const SIZE := Vector2i(1860, 270)
const NODE_CELL := Vector2i(20, 13)
const CASTLE_CELL := Vector2i(26, 26)
const CASTLES := [3, 6, 9, 12, 15, 18, 21, 24]
const REGIONS := [Vector2i(0, 250), Vector2i(250, 480), Vector2i(480, 710), Vector2i(710, 940), Vector2i(940, 1170), Vector2i(1170, 1400), Vector2i(1400, 1630), Vector2i(1630, 1860)]
const NODES := [
	Vector2(48, 196),
	Vector2(104, 150),
	Vector2(160, 198),
	Vector2(218, 142),
	Vector2(292, 182),
	Vector2(360, 212),
	Vector2(428, 152),
	Vector2(522, 198),
	Vector2(590, 146),
	Vector2(656, 196),
	Vector2(748, 206),
	Vector2(816, 158),
	Vector2(884, 198),
	Vector2(984, 150),
	Vector2(1050, 106),
	Vector2(1116, 140),
	Vector2(1206, 204),
	Vector2(1276, 222),
	Vector2(1350, 168),
	Vector2(1440, 198),
	Vector2(1514, 150),
	Vector2(1588, 192),
	Vector2(1672, 204),
	Vector2(1746, 168),
	Vector2(1822, 196),
]
const ROADS := [
	[Vector2(48, 196), Vector2(52, 189), Vector2(56, 183), Vector2(61, 178), Vector2(66, 172), Vector2(72, 168), Vector2(77, 163), Vector2(83, 159), Vector2(90, 156), Vector2(97, 153), Vector2(104, 150)],
	[Vector2(104, 150), Vector2(108, 157), Vector2(112, 163), Vector2(116, 170), Vector2(121, 175), Vector2(127, 180), Vector2(133, 185), Vector2(139, 189), Vector2(145, 192), Vector2(153, 195), Vector2(160, 198)],
	[Vector2(160, 198), Vector2(164, 190), Vector2(168, 183), Vector2(173, 176), Vector2(178, 170), Vector2(183, 164), Vector2(189, 159), Vector2(196, 154), Vector2(203, 150), Vector2(210, 146), Vector2(218, 142)],
	[Vector2(218, 142), Vector2(224, 149), Vector2(230, 155), Vector2(237, 161), Vector2(243, 166), Vector2(251, 170), Vector2(258, 174), Vector2(266, 177), Vector2(274, 179), Vector2(283, 181), Vector2(292, 182)],
	[Vector2(292, 182), Vector2(300, 183), Vector2(307, 184), Vector2(314, 186), Vector2(322, 189), Vector2(328, 192), Vector2(335, 195), Vector2(342, 198), Vector2(348, 202), Vector2(354, 207), Vector2(360, 212)],
	[Vector2(360, 212), Vector2(369, 208), Vector2(377, 204), Vector2(385, 199), Vector2(392, 194), Vector2(399, 188), Vector2(406, 182), Vector2(412, 175), Vector2(418, 168), Vector2(423, 160), Vector2(428, 152)],
	[Vector2(428, 152), Vector2(439, 154), Vector2(449, 156), Vector2(460, 159), Vector2(469, 163), Vector2(479, 167), Vector2(488, 172), Vector2(497, 177), Vector2(506, 184), Vector2(514, 190), Vector2(522, 198)],
	[Vector2(522, 198), Vector2(530, 195), Vector2(538, 191), Vector2(546, 187), Vector2(553, 183), Vector2(560, 178), Vector2(567, 172), Vector2(573, 166), Vector2(579, 160), Vector2(585, 153), Vector2(590, 146)],
	[Vector2(590, 146), Vector2(598, 149), Vector2(606, 152), Vector2(613, 156), Vector2(620, 161), Vector2(627, 165), Vector2(634, 171), Vector2(640, 176), Vector2(646, 182), Vector2(651, 189), Vector2(656, 196)],
	[Vector2(656, 196), Vector2(665, 200), Vector2(674, 203), Vector2(683, 206), Vector2(692, 208), Vector2(701, 209), Vector2(710, 210), Vector2(720, 210), Vector2(729, 209), Vector2(738, 208), Vector2(748, 206)],
	[Vector2(748, 206), Vector2(754, 199), Vector2(759, 193), Vector2(765, 187), Vector2(772, 182), Vector2(779, 177), Vector2(785, 172), Vector2(793, 168), Vector2(800, 164), Vector2(808, 161), Vector2(816, 158)],
	[Vector2(816, 158), Vector2(822, 164), Vector2(827, 170), Vector2(833, 175), Vector2(840, 180), Vector2(846, 184), Vector2(853, 188), Vector2(861, 191), Vector2(868, 194), Vector2(876, 196), Vector2(884, 198)],
	[Vector2(884, 198), Vector2(892, 189), Vector2(900, 181), Vector2(909, 174), Vector2(919, 168), Vector2(928, 162), Vector2(939, 158), Vector2(949, 155), Vector2(960, 152), Vector2(972, 151), Vector2(984, 150)],
	[Vector2(984, 150), Vector2(992, 148), Vector2(1000, 145), Vector2(1007, 142), Vector2(1014, 138), Vector2(1021, 134), Vector2(1027, 129), Vector2(1033, 124), Vector2(1039, 119), Vector2(1045, 112), Vector2(1050, 106)],
	[Vector2(1050, 106), Vector2(1058, 107), Vector2(1065, 109), Vector2(1072, 112), Vector2(1079, 114), Vector2(1086, 118), Vector2(1092, 121), Vector2(1099, 125), Vector2(1105, 130), Vector2(1110, 135), Vector2(1116, 140)],
	[Vector2(1116, 140), Vector2(1122, 150), Vector2(1129, 160), Vector2(1137, 168), Vector2(1145, 176), Vector2(1153, 183), Vector2(1163, 189), Vector2(1173, 194), Vector2(1183, 198), Vector2(1194, 201), Vector2(1206, 204)],
	[Vector2(1206, 204), Vector2(1213, 204), Vector2(1221, 205), Vector2(1228, 205), Vector2(1235, 207), Vector2(1242, 208), Vector2(1249, 210), Vector2(1256, 213), Vector2(1263, 215), Vector2(1269, 218), Vector2(1276, 222)],
	[Vector2(1276, 222), Vector2(1285, 219), Vector2(1293, 215), Vector2(1302, 211), Vector2(1310, 206), Vector2(1317, 201), Vector2(1324, 195), Vector2(1331, 189), Vector2(1338, 182), Vector2(1344, 175), Vector2(1350, 168)],
	[Vector2(1350, 168), Vector2(1360, 169), Vector2(1369, 170), Vector2(1379, 172), Vector2(1388, 175), Vector2(1397, 177), Vector2(1406, 181), Vector2(1415, 184), Vector2(1423, 188), Vector2(1432, 193), Vector2(1440, 198)],
	[Vector2(1440, 198), Vector2(1449, 196), Vector2(1458, 193), Vector2(1466, 189), Vector2(1474, 185), Vector2(1481, 181), Vector2(1489, 176), Vector2(1495, 170), Vector2(1502, 164), Vector2(1508, 157), Vector2(1514, 150)],
	[Vector2(1514, 150), Vector2(1523, 152), Vector2(1531, 155), Vector2(1539, 157), Vector2(1547, 161), Vector2(1554, 165), Vector2(1562, 169), Vector2(1569, 174), Vector2(1575, 180), Vector2(1582, 186), Vector2(1588, 192)],
	[Vector2(1588, 192), Vector2(1596, 196), Vector2(1604, 199), Vector2(1612, 201), Vector2(1621, 203), Vector2(1629, 205), Vector2(1637, 206), Vector2(1646, 206), Vector2(1655, 206), Vector2(1663, 205), Vector2(1672, 204)],
	[Vector2(1672, 204), Vector2(1678, 198), Vector2(1685, 193), Vector2(1692, 188), Vector2(1699, 184), Vector2(1706, 180), Vector2(1713, 176), Vector2(1721, 174), Vector2(1729, 171), Vector2(1737, 169), Vector2(1746, 168)],
	[Vector2(1746, 168), Vector2(1753, 174), Vector2(1759, 178), Vector2(1766, 183), Vector2(1774, 186), Vector2(1781, 190), Vector2(1789, 192), Vector2(1797, 194), Vector2(1805, 195), Vector2(1813, 196), Vector2(1822, 196)],
]
const ROAD_KIND := ["dirt", "dirt", "dirt", "dirt", "dirt", "dirt", "dirt", "dirt", "dirt", "dirt", "dirt", "dirt", "cloud", "cloud", "cloud", "cloud", "plank", "plank", "plank", "dirt", "dirt", "dirt", "dirt", "dirt"]
