#!/usr/bin/env python3
"""Level authoring for mario-clone.

    python3 tools/make_levels.py [--preview]

Levels are BUILT here with small helper calls (ground, pipe, blocks, coin
arcs, enemies, ...) and EMITTED as levels/level_<id>.gd — a plain GDScript
file holding the ASCII grid plus metadata (start, flag, warps, areas). The
ASCII grid is what level.gd reads; it stays human-readable in the repo.
--preview additionally renders each level to a PNG using the real tiles and
sprites so the whole layout can be checked at a glance.

Grid legend (one char per 16x16 cell, row 0 = top):
  .  empty            #  grass ground (autotiled)   c  cave ground (autotiled)
  X  hard block       w  cave wall brick (solid)    =  log bridge (one-way)
  B  brick            ?  ?-block (coin)             M  ?-block (power-up)
  Y  ?-block (dragon egg)  S brick (star)  C brick (10 coins)  U brick (1-UP)
  h  hidden 1-UP block
  P  pipe top-left (body extends down to the next solid cell)
  W  warp pipe top-left (enterable, see WARPS)
  >  side pipe mouth (top cell, 2 high; body extends right)
  o  coin             g  walking mushroom enemy
  decorations: * bush  + small bush  f flower  t grass tuft  r rock
               s sign  n fence
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEVEL_DIR = os.path.join(ROOT, "levels")
PREVIEW = "--preview" in sys.argv
PREVIEW_DIR = os.environ.get("PREVIEW_DIR", "/tmp")
ROWS = 20
GROUND = 17          # top row of the default ground
SOLID = set("#cXwBP W?MYSCUh>")


class Level:
    def __init__(self, lid, name, cols, time=400, theme="grass"):
        self.id = lid
        self.name = name
        self.cols = cols
        self.time = time
        self.theme = theme
        self.g = [["."] * cols for _ in range(ROWS)]
        self.start = (3, GROUND - 1)
        self.flag = None
        self.castle = None
        self.checkpoints = []
        self.warps = []
        self.areas = {}

    # ---------------------------------------------------------------- basics
    def set(self, c, r, ch):
        if 0 <= c < self.cols and 0 <= r < ROWS:
            self.g[r][c] = ch

    def get(self, c, r):
        if 0 <= c < self.cols and 0 <= r < ROWS:
            return self.g[r][c]
        return "."

    def fill(self, c0, c1, r0, r1, ch):
        for c in range(c0, c1 + 1):
            for r in range(r0, r1 + 1):
                self.set(c, r, ch)

    def ground(self, c0, c1, top=GROUND, ch="#"):
        self.fill(c0, c1, 0, ROWS - 1, ".") if False else None
        self.fill(c0, c1, top, ROWS - 1, ch)

    def pit(self, c0, c1):
        self.fill(c0, c1, 0, ROWS - 1, ".")

    def ledge(self, c0, c1, top, depth=2, ch="#"):
        """floating grass ledge"""
        self.fill(c0, c1, top, top + depth - 1, ch)

    def bridge(self, c0, c1, r):
        self.fill(c0, c1, r, r, "=")

    def blocks(self, c, r, s):
        for i, ch in enumerate(s):
            if ch != " ":
                self.set(c + i, r, ch)

    def coins(self, c, r, n, step=1):
        for i in range(n):
            self.set(c + i * step, r, "o")

    def coin_arc(self, c, r, n):
        """coins along a parabola over a gap/obstacle, r = apex row"""
        mid = (n - 1) / 2.0
        for i in range(n):
            d = abs(i - mid) / max(mid, 1)
            self.set(c + i, r + int(round(d * d * 2.2)), "o")

    def enemy(self, c, r=None):
        if r is None:
            r = self.surface(c) - 1
        self.set(c, r, "g")

    def surface(self, c):
        for r in range(ROWS):
            if self.g[r][c] in "#cX":
                return r
        return ROWS

    def decor(self, c, ch, r=None):
        if r is None:
            r = self.surface(c) - 1
        if self.get(c, r) == ".":
            self.set(c, r, ch)

    def stairs(self, c, n, up=True, base=GROUND):
        for i in range(n):
            h = i + 1 if up else n - i
            for k in range(h):
                self.set(c + i, base - 1 - k, "X")

    def pipe(self, c, h, warp=False, base=None):
        base = self.surface(c) if base is None else base
        top = base - h
        self.set(c, top, "W" if warp else "P")
        # body cells stay '.', level.gd extends the pipe down to the ground
        return (c, top)

    def side_pipe(self, c, r):
        self.set(c, r, ">")
        return (c, r)

    # ---------------------------------------------------------------- output
    def emit(self):
        path = os.path.join(LEVEL_DIR, "level_%s.gd" % self.id.replace("-", "_"))
        rows = ["".join(r) for r in self.g]
        with open(path, "w", encoding="utf-8") as fh:
            fh.write("extends RefCounted\n\n")
            fh.write("## GENERATED by tools/make_levels.py — edit the generator, not this file.\n")
            fh.write("## Legend: see the docstring at the top of tools/make_levels.py.\n\n")
            fh.write('const ID := "%s"\n' % self.id)
            fh.write('const NAME := "%s"\n' % self.name)
            fh.write("const TIME := %d\n" % self.time)
            fh.write("const START := Vector2i(%d, %d)\n" % self.start)
            fh.write("const FLAG := Vector2i(%d, %d)\n" % self.flag)
            fh.write("const CASTLE := Vector2i(%d, %d)\n" % self.castle)
            fh.write("const CHECKPOINTS := [%s]\n" % ", ".join("Vector2i(%d, %d)" % p for p in self.checkpoints))
            fh.write("const AREAS := {\n")
            for k, (c0, c1, theme) in self.areas.items():
                fh.write('\t"%s": {"from": %d, "to": %d, "theme": "%s"},\n' % (k, c0, c1, theme))
            fh.write("}\n")
            fh.write("const WARPS := [\n")
            for w in self.warps:
                fh.write('\t{"entry": Vector2i(%d, %d), "kind": "%s", "arrive": Vector2i(%d, %d), '
                         '"arrive_kind": "%s", "area": "%s"},\n'
                         % (w["entry"][0], w["entry"][1], w["kind"], w["arrive"][0], w["arrive"][1],
                            w["arrive_kind"], w["area"]))
            fh.write("]\n")
            fh.write("const GRID := [\n")
            for r in rows:
                fh.write('\t"%s",\n' % r)
            fh.write("]\n")
        print("  %s  (%d x %d)" % (os.path.relpath(path, ROOT), self.cols, ROWS))
        if PREVIEW:
            render_preview(self, os.path.join(PREVIEW_DIR, "level_%s.png" % self.id))


# =========================================================================
# 1-1  "Green Hills" — grass & earth, long, pipes + coin room, dragon egg
# =========================================================================
def level_1_1():
    L = Level("1-1", "GREEN HILLS", 312, time=400)
    MAIN_END = 262
    L.ground(0, MAIN_END - 1)
    L.start = (3, GROUND - 1)

    # --- start meadow ------------------------------------------------------
    L.decor(1, "s")
    L.decor(7, "*")
    L.decor(12, "f")
    L.decor(13, "t")
    L.blocks(16, 13, "?")
    L.blocks(21, 13, "BMB?B")
    L.blocks(23, 9, "?")
    L.enemy(24)
    L.decor(28, "+")
    L.decor(31, "f")

    # --- pipe field ----------------------------------------------------------
    L.pipe(33, 2)
    L.enemy(38)
    L.pipe(42, 3)
    L.decor(46, "t")
    L.enemy(48)
    L.enemy(50)
    warp_in = L.pipe(53, 4, warp=True)
    L.decor(57, "*")
    L.pipe(61, 4)
    L.enemy(65)

    # --- first hill with a hidden 1-UP ---------------------------------------
    L.fill(68, 76, 15, GROUND - 1, "#")         # plateau two tiles higher
    L.fill(71, 74, 13, 14, "#")                 # summit
    L.set(72, 9, "h")
    L.coins(71, 11, 4)
    L.decor(69, "f")
    L.decor(76, "t")
    L.enemy(75)

    # --- pit with a coin arc ---------------------------------------------------
    L.pit(80, 82)
    L.coin_arc(79, 12, 5)
    L.decor(85, "r")

    # --- brick run: low row + a long high row with enemies on top -------------
    L.blocks(88, 13, "BMB")
    L.blocks(92, 9, "BBBBBBBB")
    L.enemy(94, 8)
    L.enemy(97, 8)
    L.blocks(103, 9, "BBB?")
    L.blocks(106, 13, "C")
    L.enemy(101)
    L.enemy(103)
    L.blocks(112, 13, "B??B")
    L.blocks(113, 9, "o o")
    L.blocks(118, 13, "S")
    L.decor(110, "*")
    L.decor(121, "n")
    L.decor(122, "n")

    # --- dragon egg + a long field to ride through -------------------------
    L.blocks(128, 13, "BYB")
    L.enemy(136)
    L.enemy(138)
    L.enemy(140)
    L.decor(133, "f")
    L.decor(134, "f")
    L.checkpoints.append((142, GROUND - 1))
    L.ledge(145, 150, 13)
    L.coins(145, 12, 6)
    L.enemy(148, 12)
    # pond crossing on a log bridge
    L.pit(155, 163)
    L.bridge(154, 164, 14)
    L.coins(156, 12, 7)
    L.enemy(160, 13)
    L.decor(167, "*")
    L.enemy(170)
    L.enemy(172)
    L.blocks(174, 13, "?B?B?")
    L.blocks(176, 9, "M")

    # --- double staircase with a gap -----------------------------------------
    L.stairs(182, 4, up=True)
    L.pit(186, 187)
    L.stairs(188, 4, up=False)
    L.coin_arc(185, 9, 4)

    # --- exit pipe of the coin room, more enemies ----------------------------
    L.pipe(196, 3)
    warp_out = L.pipe(203, 2)
    L.enemy(208)
    L.enemy(210)
    L.blocks(212, 12, "BUB")
    L.decor(215, "t")
    L.ledge(218, 222, 12)
    L.coins(218, 11, 5)
    L.enemy(225)
    L.enemy(227)
    L.pipe(230, 2)
    L.decor(233, "f")

    # --- final staircase, flag, castle ----------------------------------------
    L.stairs(236, 8, up=True)
    L.fill(244, 244, GROUND - 8, GROUND - 1, "X")
    L.flag = (252, GROUND - 1)
    L.set(252, GROUND - 1, "X")
    L.castle = (256, GROUND - 1)
    L.decor(250, "t")

    # --- coin room (bonus area), separate columns --------------------------
    B0 = 268
    B1 = 307
    L.ground(B0, B1, top=GROUND, ch="c")
    L.fill(B0, B0 + 1, 0, GROUND - 1, "w")
    L.fill(B0, B1, 0, 2, "w")
    L.fill(B1 - 1, B1, 0, GROUND - 1, "w")
    # staggered brick shelves, each reachable with a normal jump from the one
    # below (3 tiles apart), every shelf topped with coins
    L.blocks(B0 + 5, 14, "wwww")
    L.coins(B0 + 5, 13, 4)
    L.blocks(B0 + 11, 11, "wwww")
    L.coins(B0 + 11, 10, 4)
    L.blocks(B0 + 17, 8, "wwwwww")
    L.coins(B0 + 17, 7, 6)
    L.coins(B0 + 17, 6, 6)
    L.blocks(B0 + 25, 11, "wwww")
    L.coins(B0 + 25, 10, 4)
    L.coins(B0 + 10, 16, 14)
    L.coins(B0 + 10, 15, 14)
    exit_mouth = L.side_pipe(B1 - 6, GROUND - 2)
    L.fill(B1 - 5, B1 - 2, 3, GROUND - 3, "w")

    L.areas = {"main": (0, MAIN_END - 1, "grass"), "bonus": (B0, B1, "cave")}
    L.warps = [
        {"entry": warp_in, "kind": "down", "arrive": (B0 + 3, 4), "arrive_kind": "drop", "area": "bonus"},
        {"entry": exit_mouth, "kind": "right", "arrive": warp_out, "arrive_kind": "up", "area": "main"},
    ]
    return L


# =========================================================================
# preview rendering (uses the real generated art)
# =========================================================================
def render_preview(L, path):
    from PIL import Image
    gfx = os.path.join(ROOT, "assets", "graphics")
    tiles = Image.open(os.path.join(gfx, "tiles.png")).convert("RGBA")
    blocks = Image.open(os.path.join(gfx, "blocks.png")).convert("RGBA")
    shroom = Image.open(os.path.join(gfx, "enemy_shroom.png")).convert("RGBA").crop((0, 0, 18, 17))
    coin = Image.open(os.path.join(gfx, "coin.png")).convert("RGBA").crop((0, 0, 12, 16))
    decor = Image.open(os.path.join(gfx, "decor.png")).convert("RGBA")
    hero = Image.open(os.path.join(gfx, "hero_small.png")).convert("RGBA").crop((0, 0, 20, 20))
    import re
    idx = {}
    for line in open(os.path.join(ROOT, "decor_index.gd")):
        m = re.match(r'\s*"(\w+)": Rect2\((\d+), (\d+), (\d+), (\d+)\)', line)
        if m:
            n, x, y, w, h = m.group(1), *map(int, m.groups()[1:])
            idx[n] = decor.crop((x, y, x + w, y + h))
    T = 16
    W, H = L.cols * T, ROWS * T
    img = Image.new("RGBA", (W, H), (110, 170, 240, 255))

    def tile(ax, ay):
        return tiles.crop((ax * T, ay * T, ax * T + T, ay * T + T))

    def blk(i):
        return blocks.crop((i * T, 0, i * T + T, T))

    def solid_ground(c, r, ch):
        if c < 0 or c >= L.cols or r >= ROWS:
            return True
        if r < 0:
            return False
        return L.g[r][c] == ch

    deco_map = {"*": "bush_l", "+": "bush_s", "f": "flower_a", "t": "tuft", "r": "rock", "s": "sign", "n": "fence"}
    later = []
    for r in range(ROWS):
        for c in range(L.cols):
            ch = L.g[r][c]
            x, y = c * T, r * T
            if ch in "#c":
                m = 0
                if not solid_ground(c, r - 1, ch):
                    m |= 1
                if not solid_ground(c, r + 1, ch):
                    m |= 2
                if not solid_ground(c - 1, r, ch):
                    m |= 4
                if not solid_ground(c + 1, r, ch):
                    m |= 8
                row = 0 if ch == "#" else 3
                img.alpha_composite(tile(m, row), (x, y))
            elif ch == "X":
                img.alpha_composite(blk(7), (x, y))
            elif ch == "w":
                img.alpha_composite(blk(6), (x, y))
            elif ch == "=":
                img.alpha_composite(tile(6, 1), (x, y))
            elif ch in "?MY":
                img.alpha_composite(blk(0), (x, y))
            elif ch in "BSCU":
                img.alpha_composite(blk(5), (x, y))
            elif ch == "h":
                pass
            elif ch in "PW":
                img.alpha_composite(tile(0, 2), (x, y))
                img.alpha_composite(tile(1, 2), (x + T, y))
                rr = r + 1
                while rr < ROWS and L.g[rr][c] not in "#cXw":
                    img.alpha_composite(tile(2, 2), (c * T, rr * T))
                    img.alpha_composite(tile(3, 2), (c * T + T, rr * T))
                    rr += 1
            elif ch == ">":
                img.alpha_composite(tile(4, 2), (x, y))
                img.alpha_composite(tile(5, 2), (x, y + T))
                cc = c + 1
                while cc < L.cols and L.g[r][cc] == ".":
                    img.alpha_composite(tile(6, 2), (cc * T, y))
                    img.alpha_composite(tile(7, 2), (cc * T, y + T))
                    cc += 1
            elif ch == "o":
                later.append((coin, x + 2, y))
            elif ch == "g":
                later.append((shroom, x - 1, y - 1))
            elif ch in deco_map:
                d = idx[deco_map[ch]]
                later.append((d, x + (T - d.size[0]) // 2, y + T - d.size[1]))
    for im, x, y in later:
        img.alpha_composite(im, (x, y))
    if L.flag:
        c, r = L.flag
        pole = idx["pole"]
        for k in range(1, 10):
            img.alpha_composite(pole, (c * T + 6, (r - k) * T))
        img.alpha_composite(idx["pole_ball"], (c * T + 4, (r - 10) * T + 8))
        img.alpha_composite(idx["flag"], (c * T - 9, (r - 9) * T + 2))
    if L.castle:
        c, r = L.castle
        cs = idx["castle"]
        img.alpha_composite(cs, (c * T, (r + 1) * T - cs.size[1]))
    sc, sr = L.start
    img.alpha_composite(hero, (sc * T - 2, (sr + 1) * T - 20))
    # split into strips so it stays readable
    strip_w = 64 * T
    n = (W + strip_w - 1) // strip_w
    out = Image.new("RGBA", (strip_w, n * (H + 8)), (30, 30, 30, 255))
    for i in range(n):
        out.paste(img.crop((i * strip_w, 0, min(W, (i + 1) * strip_w), H)), (0, i * (H + 8)))
    out.save(path)


if __name__ == "__main__":
    os.makedirs(LEVEL_DIR, exist_ok=True)
    level_1_1().emit()
